language: python
# The travis Python version is unrelated to the version we build and test
# with.  This is set with the MB_PYTHON_VERSION variable.
python: 3.5
sudo: required
dist: trusty
services: docker
osx_image: xcode6.4

matrix:
  exclude:
    # Exclude the default Python 3.5 build
    - python: 3.5
  include:
    - os: linux
      env: MB_PYTHON_VERSION=2.7
    - os: linux
      env:
        - MB_PYTHON_VERSION=2.7
        - UNICODE_WIDTH=16
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.5
        - NP_BUILD_DEP=numpy==1.9.3
        - NP_TEST_DEP=numpy==1.9.3
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.6
        - NP_BUILD_DEP=numpy==1.11.3
        - NP_TEST_DEP=numpy==1.11.3
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.7
        - NP_BUILD_DEP=numpy==1.17.2
        - NP_TEST_DEP=numpy==1.17.2
